### PR TITLE
Make changing port and hostname possible with environment variables

### PR DESCRIPTION
**Pull request by tiloio**
I added the option to change the port and hostname.
For that I adapted the README.md.

### CODE REVIEW

**Comment by dbushell** [comment]
Good idea.

Do you think the `jsr:@safe-env/safe-env` dependency is necessary? I'd prefer to avoid any extra dependencies.

I think we could just do something like:

```ts
Deno.serve(
  {
    port: Number.parseInt(Deno.env.get('PORT') ?? '8000'),
    hostname: Deno.env.get('HOST') ?? '0.0.0.0'
  }
```

[`Deno.serve`](https://docs.deno.com/api/deno/~/Deno.serve#function_serve_2) defaults to `0.0.0.0` so I'd suggest that as default.

I don't think the `safe-env` validation is necessary. There is no security issue and invalid values will throw immediately anyway.

**Comment by tiloio** [comment]
Now everythin should be fine without a dependency :)

**Comment by dbushell** [comment]
Thanks! one last thing, can we keep the default hostname as `0.0.0.0` to match the [Deno default](https://docs.deno.com/api/deno/~/Deno.serve#function_serve_2):

> The default is port 8000 on hostname "0.0.0.0".

otherwise it could break existing deployments if the default changes

**Comment by tiloio** [comment]
> Thanks! one last thing, can we keep the default hostname as `0.0.0.0` to match the [Deno default](https://docs.deno.com/api/deno/~/Deno.serve#function_serve_2):
> 
> > The default is port 8000 on hostname "0.0.0.0".
> 
> otherwise it could break existing deployments if the default changes

Now everything should be fine :)

**Comment by dbushell** [comment]
@tiloio great stuff! sorry to be a real pain, was this formatted without `deno fmt`? I see a few commas removed that `deno fmt` usually adds. Anyway, I'll get this merged on Monday, thanks!

**Pull request merged**
